### ISSUE TITLE
[Question] Is it possible to implement with custom dialog style

### ISSUE THREAD

**Issue by ozankonur** [hendraanggrian/countrydialog#1]
Is it possible to implement with custom dialog style ? 
Like;
 new CountryDialog.Builder(SignUpActivity.this,R.style.customStyle)

**Comment by hendraanggrian** [comment]
Currently no, but it's not tough to implement it. But I haven't updated this library for a while because I keep wondering whether or not this lib should be rewritten in Kotlin like my other libraries. I'll add this feature when I make the decision, probably the end of the week.
